spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=malcolm

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=ecom-proj-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.stdio.enabled=true
logging.pattern.console=
