server.port=9000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./authdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JWT Configuration
security.jwt.token.secret-key=ecom-demo-secret-key-very-long-secret-key-for-hs256
security.jwt.token.expire-length=3600000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

