server.port=9090

# OpenAI Configuration (Used for Groq provider)
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile


# MCP Client Configuration (Manual)
spring.ai.mcp.client.enabled=false
spring.ai.mcp.client.toolcallback.enabled=false

# Force Servlet type to avoid conflicts with WebFlux
spring.main.web-application-type=servlet

# Logging configurations
logging.level.org.springframework.ai=DEBUG
logging.level.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.boot=INFO
