server.port=9090

# OpenAI Configuration (Used for Groq provider)
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile


# MCP Client Configuration (Spring AI auto-config)
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.sse.connections.mcp-server.url=http://localhost:9091/sse
spring.ai.mcp.client.toolcallback.enabled=true

# Logging configurations
logging.level.org.springframework.ai=DEBUG
logging.level.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.boot=INFO

